import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import {
  ANALYSIS_STATUSES,
  CASE_MEMBER_ROLES,
  CASE_STATUSES,
  CONVERSATION_CHANNELS,
  CONVERSATION_STATUSES,
  DELIVERY_STATUSES,
  DOCUMENT_STATUSES,
  ESCALATION_STATUSES,
  MESSAGE_DIRECTIONS,
  MESSAGE_KINDS,
  PERSON_ROLES,
  VERIFICATION_STATUSES,
  type CaseAnalysis,
  type DocumentMetadata,
} from '@lexora/shared';

/**
 * The nine domain tables.
 *
 * Three conventions hold throughout:
 *
 * 1. **Identifiers** are UUIDs generated by PostgreSQL (`gen_random_uuid()`, built in
 *    since PG 13), so a writer never has to invent an id to build a graph.
 * 2. **Instants** are `timestamptz`. A case additionally stores its IANA zone, because
 *    an instant alone cannot render a hearing time the way a court states it.
 * 3. **Deletes do not cascade through case history.** Relationships default to
 *    `restrict`; `set null` appears only where the column is already nullable and
 *    losing the pointer is harmless. Nothing in this schema lets deleting a person
 *    quietly erase the record of a case.
 *
 * ## Cross-case ownership
 *
 * Every table that carries both a `case_id` and a pointer to a parent row enforces
 * agreement between the two with a **composite foreign key**, not an application check.
 * That requires a `unique (id, case_id)` on each parent — redundant with the primary
 * key as storage, but it is what makes PostgreSQL itself reject
 * `message.case_id <> conversation.case_id`. Those unique constraints exist for that
 * single purpose and are marked below.
 *
 * Because PostgreSQL composite foreign keys default to `MATCH SIMPLE`, a row with a
 * NULL in the pointer column satisfies the constraint regardless of its `case_id`.
 * That is exactly the wanted behavior for optional parents such as a deadline's source.
 *
 * ## Blank strings in uniqueness columns
 *
 * Every text column that takes part in a uniqueness or idempotency decision carries a
 * `_not_blank` check. `''` is not a missing value to PostgreSQL: it satisfies NOT NULL
 * and it occupies the unique slot. An empty `trigger_key` is the sharp case — two
 * unrelated analyses would collide on it, and the second would be handed the first's
 * result as though it were its own. A blank value must be rejected, not deduplicated.
 */

// ---------------------------------------------------------------------------
// Enum types
// ---------------------------------------------------------------------------

export const personRole = pgEnum('person_role', PERSON_ROLES);
export const caseStatus = pgEnum('case_status', CASE_STATUSES);
export const caseMemberRole = pgEnum('case_member_role', CASE_MEMBER_ROLES);
export const conversationChannel = pgEnum('conversation_channel', CONVERSATION_CHANNELS);
export const conversationStatus = pgEnum('conversation_status', CONVERSATION_STATUSES);
export const messageDirection = pgEnum('message_direction', MESSAGE_DIRECTIONS);
export const messageKind = pgEnum('message_kind', MESSAGE_KINDS);
export const deliveryStatus = pgEnum('delivery_status', DELIVERY_STATUSES);
export const documentStatus = pgEnum('document_status', DOCUMENT_STATUSES);
export const verificationStatus = pgEnum('verification_status', VERIFICATION_STATUSES);
export const analysisStatus = pgEnum('analysis_status', ANALYSIS_STATUSES);
export const escalationStatus = pgEnum('escalation_status', ESCALATION_STATUSES);

const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();

// ---------------------------------------------------------------------------
// people
// ---------------------------------------------------------------------------

export const people = pgTable(
  'people',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    displayName: text('display_name').notNull(),
    /** E.164, normalized before it reaches this column. Routing key, not a credential. */
    phoneE164: text('phone_e164').notNull(),
    role: personRole('role').notNull(),
    /** Non-null means explicitly enrolled in the demo; null means known but not enrolled. */
    enrolledAt: timestamp('enrolled_at', { withTimezone: true }),
    /** Opens this recipient's 24-hour WhatsApp service window. Per person, never shared. */
    lastWhatsappInboundAt: timestamp('last_whatsapp_inbound_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    // One person per number: the routing lookup must never find two candidates.
    unique('people_phone_e164_key').on(t.phoneE164),
    // Defense in depth behind `normalizePhone`: a national number cannot land here
    // even if some future caller forgets to normalize.
    check('people_phone_e164_is_e164', sql`${t.phoneE164} ~ '^\\+[1-9][0-9]{6,14}$'`),
    check('people_display_name_not_blank', sql`length(btrim(${t.displayName})) > 0`),
  ],
);

// ---------------------------------------------------------------------------
// cases
// ---------------------------------------------------------------------------

export const cases = pgTable(
  'cases',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    title: text('title').notNull(),
    status: caseStatus('status').notNull().default('open'),
    /** Explicit field. Never derived from a phone number's country code. */
    jurisdiction: text('jurisdiction').notNull(),
    language: text('language').notNull(),
    /** IANA zone name. Checked against the host zone database in the write path. */
    timezone: text('timezone').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    check('cases_title_not_blank', sql`length(btrim(${t.title})) > 0`),
    check('cases_jurisdiction_not_blank', sql`length(btrim(${t.jurisdiction})) > 0`),
    check('cases_language_not_blank', sql`length(btrim(${t.language})) > 0`),
    check('cases_timezone_not_blank', sql`length(btrim(${t.timezone})) > 0`),
    // No index on `status`: it has two values, and `getActiveCase` reaches a case
    // through `case_members` and then filters the row it already has.
  ],
);

// ---------------------------------------------------------------------------
// case_members
// ---------------------------------------------------------------------------

export const caseMembers = pgTable(
  'case_members',
  {
    caseId: uuid('case_id').notNull(),
    personId: uuid('person_id').notNull(),
    role: caseMemberRole('role').notNull(),
    isPrimary: boolean('is_primary').notNull().default(false),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    primaryKey({ columns: [t.caseId, t.personId], name: 'case_members_pkey' }),
    // `restrict` both ways: removing a person or a case must not silently drop the
    // record that they were party to it.
    foreignKey({
      name: 'case_members_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    foreignKey({
      name: 'case_members_person_id_fkey',
      columns: [t.personId],
      foreignColumns: [people.id],
    }).onDelete('restrict'),
    // The design's "one primary lawyer per case", enforced by PostgreSQL rather than
    // by a read-then-write race in application code.
    uniqueIndex('case_members_one_primary_lawyer_idx')
      .on(t.caseId)
      .where(sql`${t.role} = 'lawyer' AND ${t.isPrimary}`),
    // Reverse lookup: `getActiveCase(personId)` walks memberships to find open cases.
    // A person may be a member of many cases; that is what makes `ambiguous` reachable.
    index('case_members_person_id_idx').on(t.personId),
    // No separate unique on (case_id, person_id): the primary key above already supplies
    // the index that `conversations`, `messages` and `escalations` reference to bind a
    // party to an actual membership of that same case.
  ],
);

// ---------------------------------------------------------------------------
// conversations
// ---------------------------------------------------------------------------

export const conversations = pgTable(
  'conversations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    personId: uuid('person_id').notNull(),
    channel: conversationChannel('channel').notNull(),
    /** Provider session identifier (a voice session). Unique when present. */
    providerSessionKey: text('provider_session_key'),
    status: conversationStatus('status').notNull().default('open'),
    summary: text('summary'),
    /**
     * The message this summary was computed through, fixing the completion cutoff.
     *
     * Only a plain foreign key: a composite one would make `conversations` and
     * `messages` reference each other's unique keys in a cycle. That the message
     * belongs to *this* conversation is checked transactionally in
     * `saveConversationSummary`.
     */
    summaryThroughMessageId: uuid('summary_through_message_id').references(
      (): AnyPgColumn => messages.id,
      { onDelete: 'restrict' },
    ),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    foreignKey({
      name: 'conversations_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    foreignKey({
      name: 'conversations_person_id_fkey',
      columns: [t.personId],
      foreignColumns: [people.id],
    }).onDelete('restrict'),
    // Ownership: a conversation can only exist for someone who is actually a member of
    // that case. PostgreSQL rejects binding a conversation to a stranger.
    foreignKey({
      name: 'conversations_case_member_fkey',
      columns: [t.caseId, t.personId],
      foreignColumns: [caseMembers.caseId, caseMembers.personId],
    }).onDelete('restrict'),
    unique('conversations_provider_session_key_key').on(t.providerSessionKey),
    // Blank would occupy the unique slot and make two voice sessions collide.
    check(
      'conversations_provider_session_key_not_blank',
      sql`${t.providerSessionKey} IS NULL OR length(btrim(${t.providerSessionKey})) > 0`,
    ),
    // One open WhatsApp thread per person per case. Voice sessions are not limited this
    // way: each call is its own conversation.
    uniqueIndex('conversations_one_open_whatsapp_idx')
      .on(t.caseId, t.personId)
      .where(sql`${t.channel} = 'whatsapp' AND ${t.status} = 'open'`),
    index('conversations_case_id_idx').on(t.caseId),
    // Composite-FK target: lets `messages` and `analyses` prove they share this
    // conversation's case.
    unique('conversations_id_case_id_key').on(t.id, t.caseId),
    // A summary must say what it covers. One-way on purpose: completion marks the
    // cutoff first and writes the summary afterwards, so a cutoff with no summary yet
    // is a legitimate `completing` state.
    check(
      'conversations_summary_requires_cutoff',
      sql`${t.summary} IS NULL OR ${t.summaryThroughMessageId} IS NOT NULL`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// messages
// ---------------------------------------------------------------------------

export const messages = pgTable(
  'messages',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    conversationId: uuid('conversation_id').notNull(),
    /**
     * The human party to this message: the author inbound, the recipient outbound.
     * Null for platform output that has no human on the other side.
     */
    personId: uuid('person_id'),
    direction: messageDirection('direction').notNull(),
    kind: messageKind('kind').notNull(),
    /** Empty string is legitimate: a media message may carry no caption. */
    text: text('text').notNull().default(''),
    provider: text('provider'),
    providerMessageId: text('provider_message_id'),
    /**
     * Caller-supplied key that makes *appending this message* idempotent, scoped to the
     * conversation.
     *
     * This is **not** HTTP request idempotency and must not be pressed into that role.
     * Request-level idempotency is a different scope — authenticated integration, route,
     * resource and key — and it has to store the canonical request hash and the original
     * response so that the same key with a different body can be answered with 409. That
     * belongs to the `api_requests` table the voice API introduces, which this column
     * cannot stand in for: it has no integration, no route and no response to replay.
     *
     * Here the scope is deliberately narrower: one conversation, one appended message.
     */
    idempotencyKey: text('idempotency_key'),
    deliveryStatus: deliveryStatus('delivery_status').notNull().default('none'),
    /** Outbound attempt history. Never prompts, never credentials. */
    metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    foreignKey({
      name: 'messages_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    // Ownership, enforced by PostgreSQL: a message cannot be attached to a conversation
    // that belongs to a different case.
    foreignKey({
      name: 'messages_conversation_case_fkey',
      columns: [t.conversationId, t.caseId],
      foreignColumns: [conversations.id, conversations.caseId],
    }).onDelete('restrict'),
    // Ownership: a named party on a message must be a member of the same case.
    // NULL `person_id` passes under MATCH SIMPLE, which is what system output needs.
    foreignKey({
      name: 'messages_case_member_fkey',
      columns: [t.caseId, t.personId],
      foreignColumns: [caseMembers.caseId, caseMembers.personId],
    }).onDelete('restrict'),
    // Provider idempotency: a redelivered Twilio webhook finds the existing row instead
    // of creating a second message. Partial, so the many rows without a provider id
    // stay out of the index.
    uniqueIndex('messages_provider_message_id_idx')
      .on(t.provider, t.providerMessageId)
      .where(sql`${t.provider} IS NOT NULL AND ${t.providerMessageId} IS NOT NULL`),
    // Caller idempotency for an appended message, scoped per conversation: the voice
    // API's `externalMessageId` is only unique within its own session. Not a substitute
    // for request-level idempotency — see the column comment.
    uniqueIndex('messages_conversation_idempotency_key_idx')
      .on(t.conversationId, t.idempotencyKey)
      .where(sql`${t.idempotencyKey} IS NOT NULL`),
    // Chronology, per the design. Total ordering: `created_at` can tie, `id` cannot.
    index('messages_conversation_chronology_idx').on(t.conversationId, t.createdAt, t.id),
    // The same ordering for case-wide reads, which is how `getCaseMessages` paginates.
    index('messages_case_chronology_idx').on(t.caseId, t.createdAt, t.id),
    // Composite-FK target for `documents`, `deadlines` and `escalations`.
    unique('messages_id_case_id_key').on(t.id, t.caseId),
    // Inbound messages have no send lifecycle; `none` is their only valid value.
    check(
      'messages_inbound_has_no_delivery',
      sql`${t.direction} = 'outbound' OR ${t.deliveryStatus} = 'none'`,
    ),
    // A blank provider identifier would take the idempotency slot for the whole
    // provider, so a second blank delivery would be mistaken for a replay of the first.
    check(
      'messages_provider_not_blank',
      sql`${t.provider} IS NULL OR length(btrim(${t.provider})) > 0`,
    ),
    check(
      'messages_provider_message_id_not_blank',
      sql`${t.providerMessageId} IS NULL OR length(btrim(${t.providerMessageId})) > 0`,
    ),
    check(
      'messages_idempotency_key_not_blank',
      sql`${t.idempotencyKey} IS NULL OR length(btrim(${t.idempotencyKey})) > 0`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// documents
// ---------------------------------------------------------------------------

export const documents = pgTable(
  'documents',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    messageId: uuid('message_id').notNull(),
    /** Position of the attachment within its message, 0-based. */
    mediaIndex: integer('media_index').notNull(),
    /**
     * Private object key, deterministically `{caseId}/{documentId}/original`, so a
     * retried upload addresses the same object instead of orphaning the first one.
     * A key, never a URL: nothing in this schema stores a public or signed link.
     */
    storageKey: text('storage_key').notNull(),
    mimeType: text('mime_type').notNull(),
    /** Null while `pending`: the bytes have not been fetched yet. */
    byteSize: bigint('byte_size', { mode: 'number' }),
    sha256: text('sha256'),
    status: documentStatus('status').notNull().default('pending'),
    extractedText: text('extracted_text'),
    /** Validated extraction metadata: document type, summary, unverified date mentions. */
    metadata: jsonb('metadata').$type<DocumentMetadata>().notNull().default({}),
    errorCode: text('error_code'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    foreignKey({
      name: 'documents_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    // Ownership: a document cannot belong to a case other than its message's.
    foreignKey({
      name: 'documents_message_case_fkey',
      columns: [t.messageId, t.caseId],
      foreignColumns: [messages.id, messages.caseId],
    }).onDelete('restrict'),
    // One row per attachment slot: a replayed intake cannot create a second placeholder.
    unique('documents_message_id_media_index_key').on(t.messageId, t.mediaIndex),
    // One row per object key, so a restart-time reconcile cannot find two owners.
    unique('documents_storage_key_key').on(t.storageKey),
    check('documents_media_index_non_negative', sql`${t.mediaIndex} >= 0`),
    // Blank would take the unique slot while addressing no object at all.
    check('documents_storage_key_not_blank', sql`length(btrim(${t.storageKey})) > 0`),
    check('documents_mime_type_not_blank', sql`length(btrim(${t.mimeType})) > 0`),
    // Having stored the bytes means knowing their size and digest.
    check(
      'documents_stored_has_bytes',
      sql`${t.status} NOT IN ('stored', 'extracting', 'ready') OR (${t.byteSize} IS NOT NULL AND ${t.sha256} IS NOT NULL)`,
    ),
    // `ready` is the claim that text was extracted. Empty text is a valid extraction
    // result; absent text is not.
    check(
      'documents_ready_has_text',
      sql`${t.status} <> 'ready' OR ${t.extractedText} IS NOT NULL`,
    ),
    // A terminal failure must say why, and `error_code IS NOT NULL` alone does not get
    // that: `''` satisfies it while carrying no diagnosis. A short machine-readable code
    // such as `unsupported_media_type` or `ocr_timeout` is what belongs here — enough to
    // route the failure, with no provider payload, no document content and no URL.
    check(
      'documents_terminal_has_reason',
      sql`${t.status} NOT IN ('rejected', 'failed') OR length(btrim(coalesce(${t.errorCode}, ''))) > 0`,
    ),
    check(
      'documents_error_code_not_blank',
      sql`${t.errorCode} IS NULL OR length(btrim(${t.errorCode})) > 0`,
    ),
    check('documents_byte_size_non_negative', sql`${t.byteSize} IS NULL OR ${t.byteSize} >= 0`),
    // `getCaseDocuments` reads a case's documents and `CaseContext` filters to `ready`.
    index('documents_case_id_status_idx').on(t.caseId, t.status),
    // Composite-FK target for a deadline's source document.
    unique('documents_id_case_id_key').on(t.id, t.caseId),
  ],
);

// ---------------------------------------------------------------------------
// deadlines
// ---------------------------------------------------------------------------

export const deadlines = pgTable(
  'deadlines',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    title: text('title').notNull(),
    dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
    /** The zone the deadline was stated in, which is not necessarily the case's. */
    timezone: text('timezone').notNull(),
    sourceDocumentId: uuid('source_document_id'),
    sourceMessageId: uuid('source_message_id'),
    /**
     * Defaults to `unverified`, and nothing promotes it automatically. A date a model
     * read out of a document is a lead for the lawyer, not a court date.
     */
    verificationStatus: verificationStatus('verification_status').notNull().default('unverified'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    foreignKey({
      name: 'deadlines_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    // Ownership for both optional sources. `restrict` rather than `set null`: a
    // composite `set null` would try to null the NOT NULL `case_id`, and a legal
    // deadline should not outlive the evidence it came from silently anyway.
    foreignKey({
      name: 'deadlines_source_document_case_fkey',
      columns: [t.sourceDocumentId, t.caseId],
      foreignColumns: [documents.id, documents.caseId],
    }).onDelete('restrict'),
    foreignKey({
      name: 'deadlines_source_message_case_fkey',
      columns: [t.sourceMessageId, t.caseId],
      foreignColumns: [messages.id, messages.caseId],
    }).onDelete('restrict'),
    check('deadlines_title_not_blank', sql`length(btrim(${t.title})) > 0`),
    check('deadlines_timezone_not_blank', sql`length(btrim(${t.timezone})) > 0`),
    // `getDeadlines(caseId)` returns a case's deadlines in due order.
    index('deadlines_case_due_at_idx').on(t.caseId, t.dueAt, t.id),
  ],
);

// ---------------------------------------------------------------------------
// analyses
// ---------------------------------------------------------------------------

export const analyses = pgTable(
  'analyses',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    conversationId: uuid('conversation_id').notNull(),
    /**
     * Identifies the input event and revision this analysis answers, e.g.
     * `message:{id}:v1` or `document:{id}:ready:v1`. Unique, which is what makes a
     * restarted job reuse the existing result instead of paying for a second one.
     */
    triggerKey: text('trigger_key').notNull(),
    /** A validated `CaseAnalysis`. JSONB because the public contract is versioned. */
    result: jsonb('result').$type<CaseAnalysis>().notNull(),
    status: analysisStatus('status').notNull(),
    /**
     * On a `fallback` this is the model that was *attempted*, not one that answered.
     * Provenance has to record which model the failure is attributable to, so this
     * column is never blank even when no response came back.
     */
    model: text('model').notNull(),
    promptVersion: text('prompt_version').notNull(),
    schemaVersion: integer('schema_version').notNull(),
    /** Provenance snapshot: exactly what the model was shown. */
    contextMessageIds: uuid('context_message_ids')
      .array()
      .notNull()
      .default(sql`'{}'::uuid[]`),
    contextDocumentIds: uuid('context_document_ids')
      .array()
      .notNull()
      .default(sql`'{}'::uuid[]`),
    // Append-only: an analysis records one assessment at one instant and is never edited.
    createdAt: createdAt(),
  },
  (t) => [
    foreignKey({
      name: 'analyses_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    // Ownership: the conversation analysed must belong to the case recorded here.
    foreignKey({
      name: 'analyses_conversation_case_fkey',
      columns: [t.conversationId, t.caseId],
      foreignColumns: [conversations.id, conversations.caseId],
    }).onDelete('restrict'),
    unique('analyses_trigger_key_key').on(t.triggerKey),
    // The sharp case of the blank-string rule above: without this, two unrelated
    // analyses saved with an empty trigger key would collide, and `saveAnalysis` would
    // hand the second one the first's result with `existing: true`.
    check('analyses_trigger_key_not_blank', sql`length(btrim(${t.triggerKey})) > 0`),
    check('analyses_schema_version_positive', sql`${t.schemaVersion} > 0`),
    check('analyses_model_not_blank', sql`length(btrim(${t.model})) > 0`),
    check('analyses_prompt_version_not_blank', sql`length(btrim(${t.promptVersion})) > 0`),
    // `CaseContext.latestAnalysis` reads the newest analysis for a case.
    index('analyses_case_created_at_idx').on(t.caseId, t.createdAt.desc(), t.id.desc()),
    // Composite-FK target for `escalations`.
    unique('analyses_id_case_id_key').on(t.id, t.caseId),
  ],
);

// ---------------------------------------------------------------------------
// escalations
// ---------------------------------------------------------------------------

export const escalations = pgTable(
  'escalations',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    caseId: uuid('case_id').notNull(),
    analysisId: uuid('analysis_id').notNull(),
    /** Null when the case has no assigned lawyer, which is a visible failure. */
    lawyerId: uuid('lawyer_id'),
    outboundMessageId: uuid('outbound_message_id'),
    status: escalationStatus('status').notNull().default('pending'),
    reason: text('reason').notNull(),
    providerMessageId: text('provider_message_id'),
    errorCode: text('error_code'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    foreignKey({
      name: 'escalations_case_id_fkey',
      columns: [t.caseId],
      foreignColumns: [cases.id],
    }).onDelete('restrict'),
    // Ownership: the analysis escalated must belong to the case recorded here.
    foreignKey({
      name: 'escalations_analysis_case_fkey',
      columns: [t.analysisId, t.caseId],
      foreignColumns: [analyses.id, analyses.caseId],
    }).onDelete('restrict'),
    // Ownership: the alerted lawyer must be a member of this case.
    foreignKey({
      name: 'escalations_lawyer_case_member_fkey',
      columns: [t.caseId, t.lawyerId],
      foreignColumns: [caseMembers.caseId, caseMembers.personId],
    }).onDelete('restrict'),
    // Ownership: the outbound alert message must belong to this case.
    foreignKey({
      name: 'escalations_outbound_message_case_fkey',
      columns: [t.outboundMessageId, t.caseId],
      foreignColumns: [messages.id, messages.caseId],
    }).onDelete('restrict'),
    // One analysis escalates at most once. This is the whole duplicate-alert defense.
    unique('escalations_analysis_id_key').on(t.analysisId),
    check('escalations_reason_not_blank', sql`length(btrim(${t.reason})) > 0`),
    // `blocked_no_lawyer` is only coherent when there is in fact no lawyer.
    check(
      'escalations_blocked_no_lawyer_has_no_lawyer',
      sql`${t.status} <> 'blocked_no_lawyer' OR ${t.lawyerId} IS NULL`,
    ),
    index('escalations_case_created_at_idx').on(t.caseId, t.createdAt.desc()),
  ],
);
